//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartResponse.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDexef.Localization.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string _1000
        {
            get
            {
                return ResourceManager.GetString("1000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string _2000
        {
            get
            {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed To Fetch Data.
        /// </summary>
        public static string _2001
        {
            get
            {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some Error Occurred.
        /// </summary>
        public static string _5000
        {
            get
            {
                return ResourceManager.GetString("5000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Input Validation Error.
        /// </summary>
        public static string _6000
        {
            get
            {
                return ResourceManager.GetString("6000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : {0} Is Required.
        /// </summary>
        public static string _6001
        {
            get
            {
                return ResourceManager.GetString("6001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed: {0}  Must Be Greater Than Failed: {0}.
        /// </summary>
        public static string _6002
        {
            get
            {
                return ResourceManager.GetString("6002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Length Validation Error.
        /// </summary>
        public static string _6003
        {
            get
            {
                return ResourceManager.GetString("6003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Value Must Be Between {0} And {1}.
        /// </summary>
        public static string _6004
        {
            get
            {
                return ResourceManager.GetString("6004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Value Must Be GreaterThan {0}.
        /// </summary>
        public static string _6005
        {
            get
            {
                return ResourceManager.GetString("6005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Value Must Be LessThan {0}.
        /// </summary>
        public static string _6006
        {
            get
            {
                return ResourceManager.GetString("6006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Invalid Email.
        /// </summary>
        public static string _6007
        {
            get
            {
                return ResourceManager.GetString("6007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Invalid Items Count.
        /// </summary>
        public static string _6008
        {
            get
            {
                return ResourceManager.GetString("6008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Invalid Logo.
        /// </summary>
        public static string _6009
        {
            get
            {
                return ResourceManager.GetString("6009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Invalid Json.
        /// </summary>
        public static string _6010
        {
            get
            {
                return ResourceManager.GetString("6010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Invalid Json Empty Value.
        /// </summary>
        public static string _6011
        {
            get
            {
                return ResourceManager.GetString("6011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Failed To Deserialize.
        /// </summary>
        public static string _6012
        {
            get
            {
                return ResourceManager.GetString("6012", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Missing Default Value.
        /// </summary>
        public static string _6013
        {
            get
            {
                return ResourceManager.GetString("6013", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Missing Arabic Value.
        /// </summary>
        public static string _6014
        {
            get
            {
                return ResourceManager.GetString("6014", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Password should contain at least 1 digit.
        /// </summary>
        public static string _6015
        {
            get
            {
                return ResourceManager.GetString("6015", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Password should contain at least one alphabetic character.
        /// </summary>
        public static string _6016
        {
            get
            {
                return ResourceManager.GetString("6016", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Password should contain at least one special characters Like { ., $, ~ ,&amp;}.
        /// </summary>
        public static string _6017
        {
            get
            {
                return ResourceManager.GetString("6017", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed :Invalid Https Url.
        /// </summary>
        public static string _6018
        {
            get
            {
                return ResourceManager.GetString("6018", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Business Validation Error.
        /// </summary>
        public static string _7000
        {
            get
            {
                return ResourceManager.GetString("7000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : {0} Already Exists.
        /// </summary>
        public static string _7001
        {
            get
            {
                return ResourceManager.GetString("7001", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : {0} Not Found.
        /// </summary>
        public static string _7002
        {
            get
            {
                return ResourceManager.GetString("7002", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : {0} Is DefaultForOther.
        /// </summary>
        public static string _7003
        {
            get
            {
                return ResourceManager.GetString("7003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There&apos;re related data to this item.
        /// </summary>
        public static string _7004
        {
            get
            {
                return ResourceManager.GetString("7004", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File type Is Not supported.
        /// </summary>
        public static string _7005
        {
            get
            {
                return ResourceManager.GetString("7005", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Name Already Exists.
        /// </summary>
        public static string _7006
        {
            get
            {
                return ResourceManager.GetString("7006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : UserName Already Exists.
        /// </summary>
        public static string _7007
        {
            get
            {
                return ResourceManager.GetString("7007", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Email Already Exists.
        /// </summary>
        public static string _7008
        {
            get
            {
                return ResourceManager.GetString("7008", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Can&apos;t Delete Admin User.
        /// </summary>
        public static string _7009
        {
            get
            {
                return ResourceManager.GetString("7009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : English {0}  Already Exists.
        /// </summary>
        public static string _7010
        {
            get
            {
                return ResourceManager.GetString("7010", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed : Ar {0}  Already Exists.
        /// </summary>
        public static string _7011
        {
            get
            {
                return ResourceManager.GetString("7011", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price Level Name.
        /// </summary>
        public static string Admin_PriceLevel_Name
        {
            get
            {
                return ResourceManager.GetString("Admin.PriceLevel.Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price Level Number of Licenses.
        /// </summary>
        public static string Admin_PriceLevel_NumberOfLicenses
        {
            get
            {
                return ResourceManager.GetString("Admin.PriceLevel.NumberOfLicenses", resourceCulture);
            }
        }
    }
}
