//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartResponse.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDexef.Localization.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddOn.
        /// </summary>
        public static string AddOn
        {
            get
            {
                return ResourceManager.GetString("AddOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddOnLabel.
        /// </summary>
        public static string AddOnLabel
        {
            get
            {
                return ResourceManager.GetString("AddOnLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddOnPrice.
        /// </summary>
        public static string AddOnPrice
        {
            get
            {
                return ResourceManager.GetString("AddOnPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddOnSlider.
        /// </summary>
        public static string AddOnSlider
        {
            get
            {
                return ResourceManager.GetString("AddOnSlider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AddOnTag.
        /// </summary>
        public static string AddOnTag
        {
            get
            {
                return ResourceManager.GetString("AddOnTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application
        {
            get
            {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ApplicationLabel.
        /// </summary>
        public static string ApplicationLabel
        {
            get
            {
                return ResourceManager.GetString("ApplicationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ApplicationSlider.
        /// </summary>
        public static string ApplicationSlider
        {
            get
            {
                return ResourceManager.GetString("ApplicationSlider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ApplicationTag.
        /// </summary>
        public static string ApplicationTag
        {
            get
            {
                return ResourceManager.GetString("ApplicationTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CountryCurrency.
        /// </summary>
        public static string CountryCurrency
        {
            get
            {
                return ResourceManager.GetString("CountryCurrency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency
        {
            get
            {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CustomerReview.
        /// </summary>
        public static string CustomerReview
        {
            get
            {
                return ResourceManager.GetString("CustomerReview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee
        {
            get
            {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmployeeCountry.
        /// </summary>
        public static string EmployeeCountry
        {
            get
            {
                return ResourceManager.GetString("EmployeeCountry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EmployeeType.
        /// </summary>
        public static string EmployeeType
        {
            get
            {
                return ResourceManager.GetString("EmployeeType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature
        {
            get
            {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FileStorage.
        /// </summary>
        public static string FileStorage
        {
            get
            {
                return ResourceManager.GetString("FileStorage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FileType.
        /// </summary>
        public static string FileType
        {
            get
            {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module
        {
            get
            {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ModuleSlider.
        /// </summary>
        public static string ModuleSlider
        {
            get
            {
                return ResourceManager.GetString("ModuleSlider", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ModuleTag.
        /// </summary>
        public static string ModuleTag
        {
            get
            {
                return ResourceManager.GetString("ModuleTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدد التراخيص.
        /// </summary>
        public static string NumberOfLicenses
        {
            get
            {
                return ResourceManager.GetString("NumberOfLicenses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PriceLevel.
        /// </summary>
        public static string PriceLevel
        {
            get
            {
                return ResourceManager.GetString("PriceLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Puchasing.
        /// </summary>
        public static string Puchasing
        {
            get
            {
                return ResourceManager.GetString("Puchasing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SubscriptionType.
        /// </summary>
        public static string SubscriptionType
        {
            get
            {
                return ResourceManager.GetString("SubscriptionType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag
        {
            get
            {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax
        {
            get
            {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Addon.
        /// </summary>
        public static string VersionAddon
        {
            get
            {
                return ResourceManager.GetString("VersionAddon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string VersionFeature
        {
            get
            {
                return ResourceManager.GetString("VersionFeature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string VersionModule
        {
            get
            {
                return ResourceManager.GetString("VersionModule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string VersionPrice
        {
            get
            {
                return ResourceManager.GetString("VersionPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string VersionRelease
        {
            get
            {
                return ResourceManager.GetString("VersionRelease", resourceCulture);
            }
        }
    }
}
